"""empty message

Revision ID: b1d8d3e0d474
Revises: 
Create Date: 2023-11-16 16:23:42.799720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1d8d3e0d474'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('duration', sa.String(length=64), nullable=True),
    sa.Column('effort', sa.Integer(), nullable=True),
    sa.Column('temp', sa.Integer(), nullable=True),
    sa.Column('time_of_day', sa.String(length=32), nullable=True),
    sa.Column('date', sa.String(length=32), nullable=True),
    sa.Column('weather', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_distance'), ['distance'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_duration'), ['duration'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_effort'), ['effort'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_notes'), ['notes'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_temp'), ['temp'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_time_of_day'), ['time_of_day'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_weather'), ['weather'], unique=False)

    op.create_table('sleep',
    sa.Column('sleep_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=True),
    sa.Column('bedtime', sa.String(length=32), nullable=True),
    sa.Column('wake_up', sa.String(length=32), nullable=True),
    sa.Column('times_awoken', sa.Integer(), nullable=True),
    sa.Column('dreams_torf', sa.String(length=1), nullable=True),
    sa.Column('sleep_notes', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('sleep_id')
    )
    with op.batch_alter_table('sleep', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sleep_bedtime'), ['bedtime'], unique=False)
        batch_op.create_index(batch_op.f('ix_sleep_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sleep_dreams_torf'), ['dreams_torf'], unique=False)
        batch_op.create_index(batch_op.f('ix_sleep_sleep_notes'), ['sleep_notes'], unique=False)
        batch_op.create_index(batch_op.f('ix_sleep_wake_up'), ['wake_up'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('bio', sa.String(length=400), nullable=True),
    sa.Column('photo', sa.String(length=32), nullable=True),
    sa.Column('date_registered', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('sleep', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sleep_wake_up'))
        batch_op.drop_index(batch_op.f('ix_sleep_sleep_notes'))
        batch_op.drop_index(batch_op.f('ix_sleep_dreams_torf'))
        batch_op.drop_index(batch_op.f('ix_sleep_date'))
        batch_op.drop_index(batch_op.f('ix_sleep_bedtime'))

    op.drop_table('sleep')
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_weather'))
        batch_op.drop_index(batch_op.f('ix_run_time_of_day'))
        batch_op.drop_index(batch_op.f('ix_run_temp'))
        batch_op.drop_index(batch_op.f('ix_run_notes'))
        batch_op.drop_index(batch_op.f('ix_run_effort'))
        batch_op.drop_index(batch_op.f('ix_run_duration'))
        batch_op.drop_index(batch_op.f('ix_run_distance'))
        batch_op.drop_index(batch_op.f('ix_run_date'))

    op.drop_table('run')
    # ### end Alembic commands ###
